### ISSUE TITLE
Time management in cyclical time control

### ISSUE THREAD

**Issue by GrahamCCRL** [MKJM2/lishex#10]
Lishex is playing here - https://ccrl.live/16094

The Princhess author noticed that Lishex didn't seem to be using its time optimally.

Graham (CCRL)

**Comment by ianagbip1oti** [comment]
Hi. What I noticed when watching the game was that at one stage Lishex at 21 minutes on the clock, in a 40/15 time control. That's a lot of time banked.

What looks a little off to me (warning: not a c++ programmer) is I think the setting of info->time is ignored [here](https://github.com/MKJM2/lishex/blob/main/src/uci.cpp#L141) and [here](https://github.com/MKJM2/lishex/blob/main/src/uci.cpp#L145) , because it will just be overridden again within [this block](https://github.com/MKJM2/lishex/blob/main/src/uci.cpp#L184). This would mean Lishex is basing time management over whichever is the last of wtime/btime to be set, rather than on the one that is just for Lishex.

**Comment by GrahamCCRL** [comment]
Lishex is playing in a teams match:
https://ccrl.live/16074

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sun, Feb 18, 2024 at 6:54 PM
Subject: Fwd: 106th Amateur Series Division 9
To: ***@***.***>




---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sun, Feb 18, 2024 at 6:52 PM
Subject: 106th Amateur Series Division 9
To: Erin Dame ***@***.***>, John Merlino ***@***.***>,
juan benitez ***@***.***>, 向原 ***@***.***>, Charles
Roberson ***@***.***>, WillChing01/Pingu <
***@***.***>


106TH AMATEUR SERIES (Division 9)

Lishex 1.1.1 64-bit (relegated)
Lynx 1.3.0 64-bit
Puffin 2.0.0 64-bit
RookieMonster 1.9.9 64-bit (relegated)
Myrddin 0.90 64-bit (2022-06) (relegated)
Lambergar 0.4.1 64-bit
Betsabe II 2023 64-bit (relegated)
Lux 4.1 64-bit
Luna 2.0.0 64-bit
Admete 1.5.0 64-bit (2022-05)
FoxSEE 8.2.0 64-bit
Fornax 4 64-bit
Prophet 4.3 64-bit
Ares 2.5 64-bit

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sat, Mar 30, 2024 at 3:31 AM
Subject: 107th Amateur Series Division 9
To: Christian Sommerfeld ***@***.***>, Erik ***@***.***>,
Rasmus%20Althoff%20 ***@***.***>, Colin Jenkins ***@***.***>,
Christian Dean ***@***.***>, Erin Dame ***@***.***>, John
Merlino ***@***.***>, 向原 ***@***.***>


*107TH AMATEUR SERIES (Division 9)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
2600+8moves.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will gain automatic promotion, while the bottom engine
faces relegation. Any other changes of division will be at my discretion
and may not necessarily involve playoff matches.*

*Participants*

Fridolin 4.0 64-bit *(2022-06)* *(relegated)*
Madchess 3.2 64-bit
CT800 1.45 64-bit *(relegated)*
Boychesser 1.0 64-bit *(relegated)*
Lozza 2.5 64-bit *(relegated)*
Blunder 8.5.5 64-bit *(relegated)*
Lishex 1.1.1 64-bit
Rengar 1.3.0 64-bit *(relegated)*
RookieMonster 1.9.9 64-bit
Myrddin 0.90 64-bit *(2022-06)*
Lux 4.1 64-bit
Luna 2.0.0 64-bit
FoxSEE 8.2.0 64-bit
Prophet 4.3 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16073

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sat, Nov 23, 2024 at 9:52 AM
Subject: 113th Amateur Series Division 10
To: Erin Dame ***@***.***>, Rasmus%20Althoff%20 ***@***.***>,
Erik ***@***.***>


*113TH AMATEUR SERIES (Division 10)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU

*The top engine will gain automatic promotion and the bottom engine is
likely to be relegated. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Trinket 3.5.0 64-bit
Mess 0.3.0 64-bit
Javelin 3.0.0 64-bit
Lux 4.2 64-bit
MadChess 3.2 64-bit
Aramis 1.4.0 64-bit
CT800 1.46 64-bit
Schoenemann 0.3.0 64-bit *(promoted)*
Illumina 1.0 64-bit *(relegated)*
Lishex 1.1.1 64-bit *(promoted)*
RookieMonster 1.9.9 64-bit *(02-2023)* *(promoted)*
Bread 1.1.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16064
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
16072

**Comment by GrahamCCRL** [comment]
114TH AMATEUR SERIES (Division 11)

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

Aramis 1.4.0 64-bit (relegated)
Boychesser 1.0 64-bit (relegated)
Toad 3.0.0 64-bit (promoted)
Lishex 1.1.1 64-bit (relegated)
Tcheran 5.1 64-bit
Bread 1.1.0 64-bit (relegated)
RookieMonster 1.9.9 64-bit (02-2023) (relegated)
smol.cs 1.61 64-bit (relegated)
Betsabe II 2023 64-bit (02-2023)
Blocky 2.0.0 64-bit
Hedgehog 2.407 64-bit
Euwe 2.0.0 64-bit (promoted)
Aurora 1.22.0 64-bit
Fatalii 0.8.0 64-bit (promoted)

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16072
